name: CI-CD-PIPELINE

on:
  push:
    branches:
      - main

jobs:
  CORE-SERVICE-DEPLOYMENT:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PROD_API }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Build API Gateway application
        working-directory: services/core-service
        run: |
          npm install
          CI=false npm run build

      - name: Configure packages
        working-directory: services/core-service
        run: jq 'del(.devDependencies)' package.json > temp.json && mv temp.json package.json

      - name: Pull Vercel Environment Information
        working-directory: services/core-service
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: services/core-service
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Publish Project Artifacts to Vercel
        working-directory: services/core-service
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}

  UI-SERVICE-DEPLOYMENT:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy UI to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "services/ui-service"

  CRON-SERVICE-DEPLOYMENT:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_PROD_CRON }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        working-directory: services/cron-service
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: services/cron-service
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Publish Project Artifacts to Vercel
        working-directory: services/cron-service
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
